### PR TITLE
Added support for pydantic.Json field type in create_pydantic_model

### PR DESCRIPTION
**Pull request by heliumbrain**
Pull request for issue #48

### CODE REVIEW

**Comment by heliumbrain** [comment]
@dantownsend - please let me know if you want future Issues and/or pull requests structured differently. Haven't really worked in Github before, and it's been 10+ years since I did any proper development work :) Just trying to help out where I can and learn along the way.

**Comment by dantownsend** [comment]
@heliumbrain Great, thanks for this.

I agree that serialising it as a proper object makes sense.  I was testing it with Piccolo admin, and Piccolo admin will need a couple of tweaks to work with this change (having an object instead of a string confuses it in places).

**Comment by dantownsend** [comment]
I've made this new behaviour optional for now, until Piccolo Admin can be modified to be compatible with it.

If you're happy with it, I'll release it.

**Comment by heliumbrain** [comment]
Happy! Looks like a good solution for now 👍

**Pull request merged**
