### PR TITLE
another approach to cursor pagination

### PR DESCRIPTION
**Pull request by sinisaos**
This is another approach to cursor pagination by moving the cursor logic from the crud endpoint to a separate file and created the CursorPagination class

### CODE REVIEW

**Comment by sinisaos** [comment]
@dantownsend I pushed new code for cursor pagination but unfortunately `session_auth` test failed. All tests with 
```python
app = session_login(template_path=template_path)
client = TestClient(app)
```
or
```python
app = session_login()
client = TestClient(app) 
```
failed. I'll try to fix it but can you also look at that?

Also can you look at new cursor pagination code. It's like DRF approach. What do you think?

**Comment by dantownsend** [comment]
@sinisaos That's odd - does it say anything about why they failed?

**Comment by sinisaos** [comment]
@dantownsend This is short test summary info.
```
FAILED tests/session_auth/test_session.py::TestSessions::test_complex_custom_login_template - AssertionError: TestClient did not receive any response.
FAILED tests/session_auth/test_session.py::TestSessions::test_default_login_template - AssertionError: TestClient did not receive any response.
FAILED tests/session_auth/test_session.py::TestSessions::test_logout_get_template - AssertionError: TestClient did not receive any response.
FAILED tests/session_auth/test_session.py::TestSessions::test_logout_success - AssertionError: TestClient did not receive any response.
FAILED tests/session_auth/test_session.py::TestSessions::test_simple_custom_login_template - AssertionError: TestClient did not receive any response.
```

**Comment by dantownsend** [comment]
@sinisaos That's very odd. What was your fix?

**Comment by sinisaos** [comment]
@dantownsend Fix for `test_complex_custom_login_template`

```python
def test_complex_custom_login_template(self):
    """
    Make sure that a complex custom login template can be used, which use
    Jinja features like 'extends' and 'block'.
    """
    template_path = os.path.join(
        os.path.dirname(__file__),
        "templates",
        "complex_login_template",
        "login.html",
    )
    router = Router(
        routes=[
            Route(
                "/login/",
                session_login(template_path=template_path),
            ),
        ]
    )
    app = ExceptionMiddleware(router)
    client = TestClient(app)
    response = client.get("/login/")
    self.assertEqual(response.content, b"<p>Hello world</p>")
```
Rest is [PR](https://github.com/piccolo-orm/piccolo_api/blob/532aee7769420c6212270ffd22e809a4f07f328c/tests/session_auth/test_session.py)

**Comment by sinisaos** [comment]
@dantownsend When you have time, can you review this implementation of cursor pagination? I think it's much cleaner and I want to hear your opinion. Thanks.

**Comment by sinisaos** [comment]
Closed - open for too long without rejection, merge or activity. Feel free to reopen PR and use it again if code is still relevant.

**Comment by sinisaos** [comment]
@dantownsend I have a question? Are you planning to use the code from this PR in Piccolo API? If not, do you agree that I make a separate package for Piccolo cursor pagination (e.g. `piccolo_cursor_pagination`), that would be strictly optional and maybe would be usefull to someone. That way we won't pollute the Piccolo API code, and cursor pagination is optional anyway and doesn't work with the Piccolo Admin and Piccolo API. Do I relese it in my Github repository or even better in the Piccolo ORM organization repository (like [piccolo_docker](https://github.com/piccolo-orm/piccolo_docker)). With that way you can supervise all repo activities. What do you think about that?

**Comment by sinisaos** [comment]
@dantownsend You are absolutely right about the `PiccoloCRUD` complexity. I think separate package in Piccolo ORM would be better (cleaner) solution because cursor pagination, as you say, is more generic and doesn’t work with `Piccolo Admin` and `FastAPIWrapper`. Then I can fork it and do PR with all changes (more or less I already have everything ready). That way you can supervise all repo activities and help with fixes and suggestions.

`LimitOffset` pagination remains the default pagination and this new package would be completely optional and would probably be used in a small number of cases (but we would have it as an option).

In the Piccolo API docs we just need to mention this option and put a link to this new package if someone wants to use it.

**Comment by dantownsend** [comment]
@sinisaos OK, cool - lets create a separate repo. Can you try creating one under the piccolo_orm project? If you're not able to I might need to change your permissions.

**Comment by sinisaos** [comment]
@dantownsend Great. I'll try tomorrow.

**Pull request closed without merging**
