### PR TITLE
added a fields attribute to schema

### PR DESCRIPTION
**Pull request by sinisaos**
Related to #110

### CODE REVIEW

**Comment by dantownsend** [comment]
@sinisaos Awesome, thanks for this!

**Comment by dantownsend** [comment]
@sinisaos Yes, I'll try and get through all the PRs. Sorry about the delay.

**Comment by sinisaos** [comment]
@dantownsend Do not worry. I just wanted to remind you to take a look at them because they have a few interesting features that might be of interest to end users. Cheers.

**Comment by dantownsend** [comment]
@sinisaos This looks good, thanks. I just made a couple of changes:

 * Calling it `visible_fields_options` instead of `fields` to make it more obvious what it's for.
 * The value now changes based on `max_joins` and `exclude_secrets`

**Pull request merged**
