### PR TITLE
session_logout to use out of the box

### PR DESCRIPTION
**Pull request by sinisaos**
Based on #82

### CODE REVIEW

**Comment by dantownsend** [comment]
Thanks for this. I added some extra content to the logout template, as on reflection just having a button was a bit plain.

I think it's pretty much good to go. We just need to update the docs.

It might be possible to move the repeated bits of the template into a base template.

**Comment by sinisaos** [comment]
@dantownsend Sorry for this. I force pushed commit and delete your commits. Can you push your commits with docs and test again. Sorry for this

**Comment by dantownsend** [comment]
@sinisaos No problem.

**Comment by sinisaos** [comment]
@dantownsend Thanks a lot and sorry again. I added `base.html` and I think that should be it.

**Comment by dantownsend** [comment]
@sinisaos No problem - it was equally my fault. I've been able to merge the changes in.

**Comment by dantownsend** [comment]
Thanks for adding this.

**Pull request merged**
