### PR TITLE
moved media files from Piccolo Admin to Piccolo API

### PR DESCRIPTION
**Pull request by sinisaos**
@dantownsend I hope you meant something similar to this. Once you've checked and merged this, I'll make the changes in Piccolo Admin. Related to [this](https://github.com/piccolo-orm/piccolo_admin/issues/192) issue.

### CODE REVIEW

**Comment by dantownsend** [comment]
@sinisaos This looks great, thanks.

I think the only thing we should consider is having boto3 as an optional requirement in `setup.py`.

https://github.com/piccolo-orm/piccolo_admin/blob/master/setup.py

**Comment by sinisaos** [comment]
@dantownsend I hope that's what you meant, otherwise feel free to change it.

**Comment by sinisaos** [comment]
@dantownsend Can you please help me with these lgtm warnings?

**Comment by dantownsend** [comment]
@sinisaos I'll have a look.

**Comment by sinisaos** [comment]
@dantownsend Thanks

**Comment by dantownsend** [comment]
@sinisaos I think it's OK. Sometimes LGTM can be annoying.

**Comment by dantownsend** [comment]
@sinisaos I've published a new version of Piccolo API.

If you get a chance at any time, can you update Piccolo Admin, so it uses the latest version of Piccolo API, and imports this new code?

**Comment by sinisaos** [comment]
@dantownsend No problem. I will do it now.

**Pull request merged**
